spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/station?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: PZL3431pzl.
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
